### ISSUE TITLE
Error when running apply_patch.bat

### ISSUE THREAD

**Issue by ShiftUnderscore** [originalgrego/FZeroFinal#1]
This is the output:

`error: GP2_Hover_Cars.asm: line 268: invalid opcode or command [mvn $00,$1f]
error: GP2_Hover_Cars_Hijacks.asm: line 94: invalid opcode or command [MVN $00,$
1F]
error: GP2_Hover_Cars_Hijacks.asm: line 120: invalid opcode or command [MVN $00,
$1F]
error: GP2_Hover_Cars_Hijacks.asm: line 133: invalid opcode or command [MVN $00,
$0F]
error: GP2_Hover_Cars_Hijacks.asm: line 150: invalid opcode or command [MVN $00,
$0e]
error: GP2_Hover_Cars_Hijacks.asm: line 169: invalid opcode or command [MVN $00,
$1e]
error: GP2_Hover_Cars_Hijacks.asm: line 187: invalid opcode or command [MVN $00,
$0f]
error: GP2_Hover_Cars_Hijacks.asm: line 203: invalid opcode or command [MVN $00,
$1f]
error: GP2_Hover_Cars_Hijacks.asm: line 216: invalid opcode or command [MVN $00,
$1f]
error: GP2_Hover_Cars_Hijacks.asm: line 229: invalid opcode or command [MVN $00,
$0f]
error: GP2_Hover_Cars_Hijacks.asm: line 664: invalid opcode or command [MVN $00,
$13]
error: GP2_Hover_Cars_Hijacks.asm: line 672: invalid opcode or command [MVN $00,
$03]
error: F-Zero_Final.asm: line 925: invalid opcode or command [MVN $7F,$0C]
error: F-Zero_Final.asm: line 925: invalid opcode or command [MVN $7F,$1C]
error: F-Zero_Final.asm: line 1022: invalid opcode or command [MVN $00,$0F]
error: F-Zero_Final.asm: line 1022: invalid opcode or command [MVN $00,$1F]`

**Comment by originalgrego** [comment]
You are using the wrong version of xkas06, please use the one from smwcentral linked in the readme.

**Comment by ShiftUnderscore** [comment]
Alright, problem solved. Just FYI, "PUT XKAS V0.06 HERE.txt" links to a RomHacking.net file, which did not work.

**Comment by originalgrego** [comment]
My mistake, I updated the readme, missed that.
